#pragma once
enum HVCodec
{
	HV_CODEC_MPEG1 = 0,
	HV_CODEC_MPEG2,
	HV_CODEC_VC1,
	HV_CODEC_VP8,
	HV_CODEC_VP9,
	HV_CODEC_H264,
	HV_CODEC_H265_420,
	HV_CODEC_H265_444,
	HV_CODEC_AV1,
	HV_CODEC_UNSUPPORTED
};

enum HVChroma
{
	HV_CHROMA_FORMAT_420 = 0,
	HV_CHROMA_FORMAT_422,
	HV_CHROMA_FORMAT_444,
	HV_CHROMA_FORMAT_UNKNOWN
};

enum HVFormat
{
	HV_FORMAT_RGBA8 = 0,
	HV_FORMAT_RGB8,
	HV_FORMAT_BGRA32,
	HV_FORMAT_BGRA64_HDR10,
	HV_FORMAT_BGR24,
	HV_FORMAT_NV12,
	HV_FORMAT_P016,
};

enum HVColorSpace
{
	HV_COLORSPACE_UNKNOWN = 0,
	HV_COLORSPACE_BT601,
	HV_COLORSPACE_BT709,
	HV_COLORSPACE_ADOBE_RGB,
	HV_COLORSPACE_BT2020,
	HV_COLORSPACE_CUSTOM
};

enum HVTransfer
{
	HV_TRANSFER_UNKNOWN = 0,
	HV_TRANSFER_LINEAR,
	HV_TRANSFER_PQ,
	HV_TRANSFER_HLG,
};

enum HVToneMapper
{
	HV_TONE_MAPPER_UNKNOWN = 0,
	HV_TONE_MAPPER_REINHARD_EXT,
	HV_TONE_MAPPER_ACES
};

enum HAVError
{
	E_HV_NOT_LINKED = ERROR_GRAPHICS_ONLY_CONSOLE_SESSION_SUPPORTED + 1,
	E_HV_ALREADY_LINKED = E_HV_NOT_LINKED + 1,
	E_HV_CODEC_NOT_SUPPORTED = E_HV_ALREADY_LINKED + 1,
};